apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtalk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: estabild
    spec:
      containers:
      - name: techtalk-react-container
        image: estabild/techtalk-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      type: estabild
